export const Data = [
  {
    id: 1,
    companyName: "LiveZ",
    postedOn: "07/03/2024",
    score: 50,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Software Engineer II",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 2,
    companyName: "Browseblab",
    postedOn: "04/06/2023",
    score: 13,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Health Coach III",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 3,
    companyName: "Divanoodle",
    postedOn: "19/02/2024",
    score: 18,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Senior Cost Accountant",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 4,
    companyName: "Cogibox",
    postedOn: "22/03/2024",
    score: 21,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Paralegal",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 5,
    companyName: "Eadel",
    postedOn: "28/02/2024",
    score: 26,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Information Systems Manager",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 6,
    companyName: "Quimm",
    postedOn: "03/02/2024",
    score: 94,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Senior Developer",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 7,
    companyName: "Zooveo",
    postedOn: "30/08/2023",
    score: 16,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Help Desk Operator",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 8,
    companyName: "Cogibox",
    postedOn: "12/03/2024",
    score: 5,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Recruiter",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 9,
    companyName: "Abata",
    postedOn: "30/03/2024",
    score: 46,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Media Manager III",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 10,
    companyName: "Edgepulse",
    postedOn: "07/06/2023",
    score: 13,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Professor",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 11,
    companyName: "Eazzy",
    postedOn: "17/08/2023",
    score: 17,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Data Coordinator",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 12,
    companyName: "Tazzy",
    postedOn: "07/04/2024",
    score: 70,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Senior Sales Associate",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 13,
    companyName: "Quatz",
    postedOn: "23/03/2024",
    score: 98,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Nurse Practicioner",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 14,
    companyName: "Photobean",
    postedOn: "13/08/2023",
    score: 91,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Librarian",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 15,
    companyName: "Jabberstorm",
    postedOn: "23/02/2024",
    score: 38,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Engineer III",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 16,
    companyName: "Wikido",
    postedOn: "19/04/2024",
    score: 7,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Legal Assistant",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 17,
    companyName: "Dabtype",
    postedOn: "19/09/2023",
    score: 45,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Paralegal",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 18,
    companyName: "Avaveo",
    postedOn: "28/11/2023",
    score: 44,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Senior Quality Engineer",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 19,
    companyName: "Edgeify",
    postedOn: "23/08/2023",
    score: 48,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Environmental Specialist",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 20,
    companyName: "Fadeo",
    postedOn: "15/11/2023",
    score: 14,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Senior Quality Engineer",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 21,
    companyName: "Wikido",
    postedOn: "21/04/2024",
    score: 33,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Research Associate",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 22,
    companyName: "Blogpad",
    postedOn: "31/10/2023",
    score: 13,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Media Manager II",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 23,
    companyName: "Bluezoom",
    postedOn: "08/07/2023",
    score: 57,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Administrative Officer",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 24,
    companyName: "Skynoodle",
    postedOn: "17/04/2024",
    score: 65,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Analyst Programmer",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 25,
    companyName: "BlogXS",
    postedOn: "14/03/2024",
    score: 47,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Analyst Programmer",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 26,
    companyName: "Meevee",
    postedOn: "17/09/2023",
    score: 43,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Environmental Tech",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 27,
    companyName: "Meezzy",
    postedOn: "17/11/2023",
    score: 99,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Analog Circuit Design manager",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 28,
    companyName: "Flashspan",
    postedOn: "11/01/2024",
    score: 95,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Marketing Manager",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 29,
    companyName: "Fivechat",
    postedOn: "06/06/2023",
    score: 87,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Tax Accountant",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 30,
    companyName: "Vitz",
    postedOn: "01/07/2023",
    score: 92,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "VP Product Management",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 31,
    companyName: "Camimbo",
    postedOn: "10/07/2023",
    score: 5,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Staff Accountant IV",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 32,
    companyName: "Gigabox",
    postedOn: "21/09/2023",
    score: 6,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Research Nurse",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 33,
    companyName: "Ailane",
    postedOn: "18/05/2023",
    score: 36,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Health Coach III",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 34,
    companyName: "Divape",
    postedOn: "07/03/2024",
    score: 29,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Operator",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 35,
    companyName: "Blogtags",
    postedOn: "10/04/2024",
    score: 41,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Programmer Analyst III",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 36,
    companyName: "Bubbletube",
    postedOn: "09/12/2023",
    score: 40,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Social Worker",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 37,
    companyName: "Oozz",
    postedOn: "25/07/2023",
    score: 78,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Accounting Assistant II",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 38,
    companyName: "Browsezoom",
    postedOn: "10/08/2023",
    score: 78,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Community Outreach Specialist",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 39,
    companyName: "Leenti",
    postedOn: "01/08/2023",
    score: 29,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Geologist IV",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 40,
    companyName: "Avavee",
    postedOn: "12/05/2024",
    score: 74,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Information Systems Manager",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 41,
    companyName: "Mudo",
    postedOn: "12/12/2023",
    score: 96,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Sales Associate",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 42,
    companyName: "Innojam",
    postedOn: "25/10/2023",
    score: 94,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Database Administrator II",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 43,
    companyName: "Meembee",
    postedOn: "30/06/2023",
    score: 82,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Safety Technician II",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 44,
    companyName: "Cogidoo",
    postedOn: "02/01/2024",
    score: 98,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Legal Assistant",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 45,
    companyName: "Fivebridge",
    postedOn: "04/10/2023",
    score: 36,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Graphic Designer",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 46,
    companyName: "Jatri",
    postedOn: "17/01/2024",
    score: 81,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Food Chemist",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 47,
    companyName: "Gabtune",
    postedOn: "24/05/2023",
    score: 78,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Media Manager I",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 48,
    companyName: "Linkbuzz",
    postedOn: "29/02/2024",
    score: 34,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Operator",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 49,
    companyName: "Voomm",
    postedOn: "27/08/2023",
    score: 41,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "VP Product Management",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 50,
    companyName: "Aibox",
    postedOn: "17/04/2024",
    score: 44,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Web Developer IV",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 51,
    companyName: "Skaboo",
    postedOn: "02/09/2023",
    score: 24,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "VP Accounting",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 52,
    companyName: "Digitube",
    postedOn: "21/08/2023",
    score: 30,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Financial Advisor",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 53,
    companyName: "Dablist",
    postedOn: "11/09/2023",
    score: 93,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Graphic Designer",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 54,
    companyName: "Blogpad",
    postedOn: "26/02/2024",
    score: 34,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Help Desk Technician",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 55,
    companyName: "Vitz",
    postedOn: "16/09/2023",
    score: 64,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Automation Specialist II",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 56,
    companyName: "Wordify",
    postedOn: "25/11/2023",
    score: 40,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Quality Control Specialist",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 57,
    companyName: "Minyx",
    postedOn: "18/04/2024",
    score: 39,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Actuary",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 58,
    companyName: "Eimbee",
    postedOn: "07/07/2023",
    score: 92,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Budget/Accounting Analyst I",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 59,
    companyName: "Meezzy",
    postedOn: "20/06/2023",
    score: 84,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Software Engineer I",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 60,
    companyName: "Skinder",
    postedOn: "05/11/2023",
    score: 78,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Analyst Programmer",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 61,
    companyName: "Innotype",
    postedOn: "04/10/2023",
    score: 80,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "VP Accounting",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 62,
    companyName: "Photobug",
    postedOn: "13/02/2024",
    score: 23,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Community Outreach Specialist",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 63,
    companyName: "Tagopia",
    postedOn: "24/02/2024",
    score: 12,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Senior Sales Associate",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 64,
    companyName: "Brainlounge",
    postedOn: "20/08/2023",
    score: 70,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Social Worker",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 65,
    companyName: "Devpoint",
    postedOn: "14/02/2024",
    score: 54,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Civil Engineer",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 66,
    companyName: "Dabfeed",
    postedOn: "27/10/2023",
    score: 97,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Budget/Accounting Analyst I",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 67,
    companyName: "Yata",
    postedOn: "16/04/2024",
    score: 62,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Analyst Programmer",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 68,
    companyName: "Centidel",
    postedOn: "09/04/2024",
    score: 63,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Quality Control Specialist",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 69,
    companyName: "Zazio",
    postedOn: "28/08/2023",
    score: 19,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Legal Assistant",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 70,
    companyName: "Chatterbridge",
    postedOn: "14/01/2024",
    score: 88,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Analog Circuit Design manager",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 71,
    companyName: "Yodoo",
    postedOn: "26/12/2023",
    score: 11,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Chief Design Engineer",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 72,
    companyName: "Bubblebox",
    postedOn: "07/11/2023",
    score: 5,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Associate Professor",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 73,
    companyName: "Jamia",
    postedOn: "31/12/2023",
    score: 33,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Environmental Specialist",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 74,
    companyName: "Yata",
    postedOn: "29/09/2023",
    score: 49,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Accountant IV",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 75,
    companyName: "Youopia",
    postedOn: "01/12/2023",
    score: 65,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Teacher",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 76,
    companyName: "Realcube",
    postedOn: "30/11/2023",
    score: 76,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Nurse",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 77,
    companyName: "Thoughtworks",
    postedOn: "07/03/2024",
    score: 19,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Chief Design Engineer",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 78,
    companyName: "Flashset",
    postedOn: "20/05/2023",
    score: 62,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Associate Professor",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 79,
    companyName: "Feednation",
    postedOn: "29/04/2024",
    score: 61,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Sales Representative",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 80,
    companyName: "Skidoo",
    postedOn: "21/09/2023",
    score: 89,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Software Engineer I",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 81,
    companyName: "Nlounge",
    postedOn: "26/12/2023",
    score: 28,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "VP Product Management",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 82,
    companyName: "Linkbuzz",
    postedOn: "12/11/2023",
    score: 90,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Senior Quality Engineer",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 83,
    companyName: "Meevee",
    postedOn: "02/04/2024",
    score: 7,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Librarian",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 84,
    companyName: "Dynava",
    postedOn: "08/08/2023",
    score: 68,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Research Assistant I",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 85,
    companyName: "Flashset",
    postedOn: "17/05/2023",
    score: 19,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Accountant I",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 86,
    companyName: "Tagpad",
    postedOn: "24/08/2023",
    score: 91,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Safety Technician III",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 87,
    companyName: "Wikido",
    postedOn: "09/12/2023",
    score: 46,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Clinical Specialist",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 88,
    companyName: "Meeveo",
    postedOn: "15/05/2023",
    score: 40,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Account Executive",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 89,
    companyName: "Blognation",
    postedOn: "20/06/2023",
    score: 30,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Geologist III",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 90,
    companyName: "Digitube",
    postedOn: "20/11/2023",
    score: 87,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Analyst Programmer",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 91,
    companyName: "Jabberstorm",
    postedOn: "13/12/2023",
    score: 11,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Junior Executive",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 92,
    companyName: "Gabspot",
    postedOn: "06/05/2024",
    score: 32,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Dental Hygienist",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 93,
    companyName: "Skaboo",
    postedOn: "04/01/2024",
    score: 69,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Help Desk Operator",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 94,
    companyName: "Plajo",
    postedOn: "06/09/2023",
    score: 16,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Design Engineer",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 95,
    companyName: "Demimbu",
    postedOn: "14/11/2023",
    score: 60,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Chief Design Engineer",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 96,
    companyName: "Feednation",
    postedOn: "22/11/2023",
    score: 23,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Senior Editor",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 97,
    companyName: "Tagfeed",
    postedOn: "04/05/2024",
    score: 66,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Programmer Analyst III",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 98,
    companyName: "Ailane",
    postedOn: "27/09/2023",
    score: 99,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Legal Assistant",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 99,
    companyName: "Trudoo",
    postedOn: "04/09/2023",
    score: 54,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Physical Therapy Assistant",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
  {
    id: 100,
    companyName: "Gabcube",
    postedOn: "12/09/2023",
    score: 66,
    skills: ["UX", "Sales", "HR", "Content-writer"],
    role: "Assistant Manager",
    img: "https://i.ibb.co/SR4N25d/mployee-me-logo.jpg",
  },
];
